### PR TITLE
chore: remove release-it.d.ts, upgrade release-it.d.ts version

### LINKED ISSUE #29: 🛠 Tooling: Move release-it.d.ts to release-it or DefinitelyTyped
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/release-it-action/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

https://github.com/webpro/release-it is written in JavaScript and doesn't ship its own `.d.ts` types. The general TypeScript community consensus for packages like that is to write the types in https://github.com/DefinitelyTyped/DefinitelyTyped. That'd be better than having a `src/release-it.d.ts` checked into this repo.

Once there are TypeScript types available for the `release-it` package, we can use them here. Accepting PRs!

### Additional Info

cc @webpro as an FYI.

### PR DESCRIPTION
**Pull request by markEHVN**
## PR Checklist

- [x] Addresses an existing open issue: fixes #29 
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/release-it-action/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/release-it-action/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Upgrade release-it version, new version has type information.

### CODE REVIEW

**Comment by markEHVN** [comment]
Just curious, why do we need release-it.d.ts file? I do not see we use it in project 🤔

**Comment by JoshuaKGoldberg** [comment]
> Just curious, why do we need release-it.d.ts file? I do not see we use it in project 🤔

When I first wrote the file many months ago, the `release-it` project hadn't yet added its own types. You can see this with:

```plaintext
git checkout ed7fbb2
pnpm install
pnpm run tsc
```

```plaintext
> release-it-action@0.1.0 tsc /Users/josh/repos/release-it-action
> tsc

src/index.ts:4:23 - error TS7016: Could not find a declaration file for module 'release-it'. '/Users/josh/repos/release-it-action/node_modules/.pnpm/release-it@16.2.1_typescript@5.2.2/node_modules/release-it/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/release-it` if it exists or add a new declaration (.d.ts) file containing `declare module 'release-it';`

4 import releaseIt from "release-it";
                        ~~~~~~~~~~~~


Found 1 error in src/index.ts:4

 ELIFECYCLE  Command failed with exit code 2.
```

But, once the `release-it` dependency was automatically updated by the Renovate bot to a version with types, the `.d.ts` was no longer necessary. Looks like that was probably #300 or so.

**Review by JoshuaKGoldberg — APPROVED** [review]
Nice! I'd missed that the `release-it` had added their own types. This is great. Thanks! 🙌

**Comment by JoshuaKGoldberg** [comment]
@all-contributors please add @markehvn for code.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Pull request merged**
